### ISSUE TITLE
Marking views recyclable algorithm when in fling state

### ISSUE THREAD

**Issue by liao123abc** [devunwired/recyclerview-playground#20]
Dear Dear Dave Smith:
        
Great job! 

But could you please help me about some cofusions?

Currently I dive into your code of the FixedGirdLayoutManager, it confused me.

To make it simple, suppose it only scroll vertically.

 When slowly scrolling,RecyclerView will tell the manager to do something by  : scrollVerticallyBy()

and then detach all the views then calculate the visible rows and columns then
find the right child views that are still in the visible area. If no view is 
ready for the slot, then create a new one.

This is understandable.

But with a fling gesture, it seems that the the old and
new created child views are positioned in a quite large negtive Pos by: 

old views:
1.offsetChildrenVertical(delta); in scrollVerticallyBy() of fixedGridLayoutManager

new views:
2.layoutDecorated();   in fillGrid() of fixedGridLayoutManager

I have log them out,Plz have a look at the log :

layoutDecorated.png:
![layoutdecorated](https://cloud.githubusercontent.com/assets/9350689/10094112/4c204098-638e-11e5-84f1-04a47ef1ad80.png)

offsetChildrenVertical.png:
![offsetchildrenvertical](https://cloud.githubusercontent.com/assets/9350689/10094069/aa8a3d9c-638d-11e5-853c-2dbd46288795.png)

This confused me for a long time , I cannot figure it out:
When fling the recyclerview vertically bottom up;

1. Why we need to position the child view from a large negtive position in the y-axis , for exeample: -1766
while my recyclerView height is : 1293.   Isn't the position -1766 deem bo be invisible to my recyclerview? Then why have to attach view from here?

2. I noticed that when scrolling down, if the bottom of the fist view in the recyclerView is negetive,
you will increase the mFirstVisiblePosition by 1 to mark that  view is recyclable. This marking recyclable algorithm is a little hard to understand. Why only mark the top row of child views recyclable. How dose it work?

Please, I beg for your answers.
I have been confusing by these questions for a long time.

**Comment by devunwired** [comment]
I need a bit more information here. Your `layoutDecorated()` numbers don't make sense to me. It's note entirely clear what I'm looking at in that log. You mentioned it was during a fling upwards, but what line of the FGLM code is being logged there?

If the first number in each row is the adapter position (just a guess), then the `bottom` values should increase with each row (y-coordinate is positive in the downward direction), but they get more negative as the position number goes up. So either this log is a concatenation of different snippets in a way that I cannot work out, or one of these values is being logged incorrectly.

**Comment by pradeeshmp** [comment]
Dear Dave,
This is Pradeesh, one of your follower.
This is not realted to this issue, I have read some of your publishes while surfing.

My question, is it possible to pair two Android mobiles by bluetooth programatically with or without using GATT profile.

Actually the thing is its generating dynamic pin which needs user to be confirmed
