### ISSUE TITLE
Bug: GridDividerDecoration cannot handle rows of different heights

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [devunwired/recyclerview-playground#21]
steps to reproduce:

1. add this line in onBindViewHolder of SimpleAdapter :

        layoutParams.height=position<4?100:200;

2. run app.

3. switch to vertical grid .

4. scroll down and up.

This is what you get:

![device-2015-11-22-015723](https://cloud.githubusercontent.com/assets/5357526/11321169/69936d48-90bc-11e5-85c1-0dc22117d60e.png)

How can I solve this?

**Comment by devunwired** [comment]
Feature added in commit c5a04821f06c38ae796dcfd2ba370098320f5058

**Comment by AndroidDeveloperLB** [comment]
@devunwired Nice. Thank you !
