### ISSUE TITLE
Curious ... is this repo being maintained?

### ISSUE THREAD

**Issue by Bradleycorn** [devunwired/recyclerview-playground#36]
Looks like there haven't been any commits in several years ... is this repo being actively maintained, or no?

**Comment by devunwired** [comment]
From the [README](https://github.com/devunwired/recyclerview-playground#disclaimer):
> This repository contains sample code intended to demonstrate the capabilities of the RecyclerView layout manager APIs. It is not intended to be used as-is in applications as a library dependency, and will not be maintained as such.

**Comment by Bradleycorn** [comment]
@devunwired - Gotcha. Thanks for the info. Guess I shoulda RTFM :)
