### ISSUE TITLE
Issue on fling with curved motion (y and x axis simultaneous movement)

### ISSUE THREAD

**Issue by fmnstr** [devunwired/recyclerview-playground#6]
In FixedGridLayoutManager when scrolling with a fling motion with a slight curve, triggering an unintentional scroll on both axis (try a a fling curve motion starting from lower left corner ending to upper right corner), I can see the grid children filling the view with some delay (I see the white background with the dividers scrolling and then the grid items fill the view). If I try with fast continuous flings I can stop the grid with some grid item positions not yet filled with the appropriate views, seeing only the white backround. If I later move the grid it gets filled as normal.
I think the problem is the fast scrolling movement in both axis. Can I somehow disable the movement to the other direction when flinging? I don't care much for diagonal scrolling.
I have been using your example app, with 10 columns and a lot of rows (1500).

**Comment by devunwired** [comment]
I believe this is fixed with the latest PRs submitted by another contributor.

**Comment by nurcahyo** [comment]
Issue still valid on many rows with row height <= 50dp
